# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TheSoundOfSilence/Source.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CallMeMaybe import CommonMessages_pb2 as CallMeMaybe_dot_CommonMessages__pb2
from TheSoundOfSilence import Session_pb2 as TheSoundOfSilence_dot_Session__pb2
from TheSoundOfSilence import Picture_pb2 as TheSoundOfSilence_dot_Picture__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TheSoundOfSilence/Source.proto',
  package='Devialet.AudioSource',
  syntax='proto2',
  serialized_pb=_b('\n\x1eTheSoundOfSilence/Source.proto\x12\x14\x44\x65vialet.AudioSource\x1a CallMeMaybe/CommonMessages.proto\x1a\x1fTheSoundOfSilence/Session.proto\x1a\x1fTheSoundOfSilence/Picture.proto\"h\n\x0bSourceError\"Y\n\x04\x43ode\x12\x11\n\rInternalError\x10\x01\x12\x10\n\x0cNotSupported\x10\x02\x12\x14\n\x10PermissionDenied\x10\x03\x12\x16\n\x12ObjectNotAvailable\x10\x04\"\x18\n\x07\x45nabled\x12\r\n\x05value\x18\x01 \x02(\x08\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x02(\x0c\"\x12\n\x03Uri\x12\x0b\n\x03uri\x18\x01 \x02(\t2M\n\rSourceSession\x12<\n\x03uri\x12\x18.Devialet.AudioSource.Id\x1a\x19.Devialet.AudioSource.Uri\"\x00\x32]\n\x0f\x43onfigureSource\x12J\n\nsetEnabled\x12\x1d.Devialet.AudioSource.Enabled\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x32\xb7\x02\n\x06Source\x12\x44\n\x04logo\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1d.Devialet.AudioSource.Picture\"\x00\x12L\n\x0csessionAdded\x12\x1d.Devialet.AudioSource.Session\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12P\n\x0esessionRemoved\x12\x1f.Devialet.AudioSource.SessionId\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12G\n\x07\x62igLogo\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1d.Devialet.AudioSource.Picture\"\x00')
  ,
  dependencies=[CallMeMaybe_dot_CommonMessages__pb2.DESCRIPTOR,TheSoundOfSilence_dot_Session__pb2.DESCRIPTOR,TheSoundOfSilence_dot_Picture__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SOURCEERROR_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Devialet.AudioSource.SourceError.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='InternalError', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NotSupported', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PermissionDenied', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ObjectNotAvailable', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=171,
  serialized_end=260,
)
_sym_db.RegisterEnumDescriptor(_SOURCEERROR_CODE)


_SOURCEERROR = _descriptor.Descriptor(
  name='SourceError',
  full_name='Devialet.AudioSource.SourceError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOURCEERROR_CODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=260,
)


_ENABLED = _descriptor.Descriptor(
  name='Enabled',
  full_name='Devialet.AudioSource.Enabled',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.AudioSource.Enabled.value', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=286,
)


_ID = _descriptor.Descriptor(
  name='Id',
  full_name='Devialet.AudioSource.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Devialet.AudioSource.Id.id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=304,
)


_URI = _descriptor.Descriptor(
  name='Uri',
  full_name='Devialet.AudioSource.Uri',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='Devialet.AudioSource.Uri.uri', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=324,
)

_SOURCEERROR_CODE.containing_type = _SOURCEERROR
DESCRIPTOR.message_types_by_name['SourceError'] = _SOURCEERROR
DESCRIPTOR.message_types_by_name['Enabled'] = _ENABLED
DESCRIPTOR.message_types_by_name['Id'] = _ID
DESCRIPTOR.message_types_by_name['Uri'] = _URI

SourceError = _reflection.GeneratedProtocolMessageType('SourceError', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEERROR,
  __module__ = 'TheSoundOfSilence.Source_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.AudioSource.SourceError)
  ))
_sym_db.RegisterMessage(SourceError)

Enabled = _reflection.GeneratedProtocolMessageType('Enabled', (_message.Message,), dict(
  DESCRIPTOR = _ENABLED,
  __module__ = 'TheSoundOfSilence.Source_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.AudioSource.Enabled)
  ))
_sym_db.RegisterMessage(Enabled)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'TheSoundOfSilence.Source_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.AudioSource.Id)
  ))
_sym_db.RegisterMessage(Id)

Uri = _reflection.GeneratedProtocolMessageType('Uri', (_message.Message,), dict(
  DESCRIPTOR = _URI,
  __module__ = 'TheSoundOfSilence.Source_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.AudioSource.Uri)
  ))
_sym_db.RegisterMessage(Uri)


# @@protoc_insertion_point(module_scope)
