# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CallMeMaybe/CommonMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CallMeMaybe/CommonMessages.proto',
  package='Devialet.CallMeMaybe',
  syntax='proto2',
  serialized_pb=_b('\n CallMeMaybe/CommonMessages.proto\x12\x14\x44\x65vialet.CallMeMaybe\"\x07\n\x05\x45mpty\"\xb5\x02\n\tBaseError\"\x8d\x02\n\x04\x43ode\x12\x0b\n\x07NoError\x10\x00\x12\x0f\n\x0b\x42\x61\x64\x41rgument\x10\x01\x12\x10\n\x0cUnknownError\x10\x02\x12\x12\n\x0eInvalidRequest\x10\x03\x12\x13\n\x0fInvalidResponse\x10\x04\x12\x10\n\x0cNetworkError\x10\x05\x12\x14\n\x10UnparsableResult\x10\x06\x12\x16\n\x12\x43lientDisconnected\x10\x07\x12\x0f\n\x0b\x43lientReset\x10\x08\x12\x12\n\x0eServiceRemoved\x10\t\x12\x10\n\x0c\x43\x61llCanceled\x10\n\x12\x10\n\x0c\x43\x61llTimedOut\x10\x0b\x12\x0e\n\nCallFailed\x10\x0c\x12\x13\n\x0f\x43onnectionError\x10\r\"\x18\n\x07MaxCode\x12\r\n\tMAX_ERROR\x10\r\"\x1f\n\x0e\x44oubleProperty\x12\r\n\x05value\x18\x01 \x02(\x01\"\x1e\n\rFloatProperty\x12\r\n\x05value\x18\x01 \x02(\x02\"\x1e\n\rInt32Property\x12\r\n\x05value\x18\x01 \x02(\x05\"\x1e\n\rInt64Property\x12\r\n\x05value\x18\x01 \x02(\x03\"\x1f\n\x0eUInt32Property\x12\r\n\x05value\x18\x01 \x02(\r\"\x1f\n\x0eUInt64Property\x12\r\n\x05value\x18\x01 \x02(\x04\"\x1f\n\x0eSInt32Property\x12\r\n\x05value\x18\x01 \x02(\x11\"\x1f\n\x0eSInt64Property\x12\r\n\x05value\x18\x01 \x02(\x12\" \n\x0f\x46ixed32Property\x12\r\n\x05value\x18\x01 \x02(\x07\" \n\x0f\x46ixed64Property\x12\r\n\x05value\x18\x01 \x02(\x06\"!\n\x10SFixed32Property\x12\r\n\x05value\x18\x01 \x02(\x0f\"!\n\x10SFixed64Property\x12\r\n\x05value\x18\x01 \x02(\x10\"\x1d\n\x0c\x42oolProperty\x12\r\n\x05value\x18\x01 \x02(\x08\"\x1f\n\x0eStringProperty\x12\r\n\x05value\x18\x01 \x02(\t\"$\n\x12StringListProperty\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1e\n\rBytesProperty\x12\r\n\x05value\x18\x01 \x02(\x0c\x42\x03\x90\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BASEERROR_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Devialet.CallMeMaybe.BaseError.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoError', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BadArgument', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnknownError', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidRequest', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidResponse', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NetworkError', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnparsableResult', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ClientDisconnected', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ClientReset', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ServiceRemoved', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CallCanceled', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CallTimedOut', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CallFailed', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ConnectionError', index=13, number=13,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=82,
  serialized_end=351,
)
_sym_db.RegisterEnumDescriptor(_BASEERROR_CODE)

_BASEERROR_MAXCODE = _descriptor.EnumDescriptor(
  name='MaxCode',
  full_name='Devialet.CallMeMaybe.BaseError.MaxCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MAX_ERROR', index=0, number=13,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=353,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_BASEERROR_MAXCODE)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Devialet.CallMeMaybe.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=65,
)


_BASEERROR = _descriptor.Descriptor(
  name='BaseError',
  full_name='Devialet.CallMeMaybe.BaseError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BASEERROR_CODE,
    _BASEERROR_MAXCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=377,
)


_DOUBLEPROPERTY = _descriptor.Descriptor(
  name='DoubleProperty',
  full_name='Devialet.CallMeMaybe.DoubleProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.DoubleProperty.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=410,
)


_FLOATPROPERTY = _descriptor.Descriptor(
  name='FloatProperty',
  full_name='Devialet.CallMeMaybe.FloatProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.FloatProperty.value', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=442,
)


_INT32PROPERTY = _descriptor.Descriptor(
  name='Int32Property',
  full_name='Devialet.CallMeMaybe.Int32Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.Int32Property.value', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=474,
)


_INT64PROPERTY = _descriptor.Descriptor(
  name='Int64Property',
  full_name='Devialet.CallMeMaybe.Int64Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.Int64Property.value', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=506,
)


_UINT32PROPERTY = _descriptor.Descriptor(
  name='UInt32Property',
  full_name='Devialet.CallMeMaybe.UInt32Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.UInt32Property.value', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=539,
)


_UINT64PROPERTY = _descriptor.Descriptor(
  name='UInt64Property',
  full_name='Devialet.CallMeMaybe.UInt64Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.UInt64Property.value', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=572,
)


_SINT32PROPERTY = _descriptor.Descriptor(
  name='SInt32Property',
  full_name='Devialet.CallMeMaybe.SInt32Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.SInt32Property.value', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=605,
)


_SINT64PROPERTY = _descriptor.Descriptor(
  name='SInt64Property',
  full_name='Devialet.CallMeMaybe.SInt64Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.SInt64Property.value', index=0,
      number=1, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=638,
)


_FIXED32PROPERTY = _descriptor.Descriptor(
  name='Fixed32Property',
  full_name='Devialet.CallMeMaybe.Fixed32Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.Fixed32Property.value', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=672,
)


_FIXED64PROPERTY = _descriptor.Descriptor(
  name='Fixed64Property',
  full_name='Devialet.CallMeMaybe.Fixed64Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.Fixed64Property.value', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=706,
)


_SFIXED32PROPERTY = _descriptor.Descriptor(
  name='SFixed32Property',
  full_name='Devialet.CallMeMaybe.SFixed32Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.SFixed32Property.value', index=0,
      number=1, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=741,
)


_SFIXED64PROPERTY = _descriptor.Descriptor(
  name='SFixed64Property',
  full_name='Devialet.CallMeMaybe.SFixed64Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.SFixed64Property.value', index=0,
      number=1, type=16, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=743,
  serialized_end=776,
)


_BOOLPROPERTY = _descriptor.Descriptor(
  name='BoolProperty',
  full_name='Devialet.CallMeMaybe.BoolProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.BoolProperty.value', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=778,
  serialized_end=807,
)


_STRINGPROPERTY = _descriptor.Descriptor(
  name='StringProperty',
  full_name='Devialet.CallMeMaybe.StringProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.StringProperty.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=809,
  serialized_end=840,
)


_STRINGLISTPROPERTY = _descriptor.Descriptor(
  name='StringListProperty',
  full_name='Devialet.CallMeMaybe.StringListProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='Devialet.CallMeMaybe.StringListProperty.values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=842,
  serialized_end=878,
)


_BYTESPROPERTY = _descriptor.Descriptor(
  name='BytesProperty',
  full_name='Devialet.CallMeMaybe.BytesProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.CallMeMaybe.BytesProperty.value', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=880,
  serialized_end=910,
)

_BASEERROR_CODE.containing_type = _BASEERROR
_BASEERROR_MAXCODE.containing_type = _BASEERROR
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['BaseError'] = _BASEERROR
DESCRIPTOR.message_types_by_name['DoubleProperty'] = _DOUBLEPROPERTY
DESCRIPTOR.message_types_by_name['FloatProperty'] = _FLOATPROPERTY
DESCRIPTOR.message_types_by_name['Int32Property'] = _INT32PROPERTY
DESCRIPTOR.message_types_by_name['Int64Property'] = _INT64PROPERTY
DESCRIPTOR.message_types_by_name['UInt32Property'] = _UINT32PROPERTY
DESCRIPTOR.message_types_by_name['UInt64Property'] = _UINT64PROPERTY
DESCRIPTOR.message_types_by_name['SInt32Property'] = _SINT32PROPERTY
DESCRIPTOR.message_types_by_name['SInt64Property'] = _SINT64PROPERTY
DESCRIPTOR.message_types_by_name['Fixed32Property'] = _FIXED32PROPERTY
DESCRIPTOR.message_types_by_name['Fixed64Property'] = _FIXED64PROPERTY
DESCRIPTOR.message_types_by_name['SFixed32Property'] = _SFIXED32PROPERTY
DESCRIPTOR.message_types_by_name['SFixed64Property'] = _SFIXED64PROPERTY
DESCRIPTOR.message_types_by_name['BoolProperty'] = _BOOLPROPERTY
DESCRIPTOR.message_types_by_name['StringProperty'] = _STRINGPROPERTY
DESCRIPTOR.message_types_by_name['StringListProperty'] = _STRINGLISTPROPERTY
DESCRIPTOR.message_types_by_name['BytesProperty'] = _BYTESPROPERTY

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Empty)
  ))
_sym_db.RegisterMessage(Empty)

BaseError = _reflection.GeneratedProtocolMessageType('BaseError', (_message.Message,), dict(
  DESCRIPTOR = _BASEERROR,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.BaseError)
  ))
_sym_db.RegisterMessage(BaseError)

DoubleProperty = _reflection.GeneratedProtocolMessageType('DoubleProperty', (_message.Message,), dict(
  DESCRIPTOR = _DOUBLEPROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.DoubleProperty)
  ))
_sym_db.RegisterMessage(DoubleProperty)

FloatProperty = _reflection.GeneratedProtocolMessageType('FloatProperty', (_message.Message,), dict(
  DESCRIPTOR = _FLOATPROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.FloatProperty)
  ))
_sym_db.RegisterMessage(FloatProperty)

Int32Property = _reflection.GeneratedProtocolMessageType('Int32Property', (_message.Message,), dict(
  DESCRIPTOR = _INT32PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Int32Property)
  ))
_sym_db.RegisterMessage(Int32Property)

Int64Property = _reflection.GeneratedProtocolMessageType('Int64Property', (_message.Message,), dict(
  DESCRIPTOR = _INT64PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Int64Property)
  ))
_sym_db.RegisterMessage(Int64Property)

UInt32Property = _reflection.GeneratedProtocolMessageType('UInt32Property', (_message.Message,), dict(
  DESCRIPTOR = _UINT32PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.UInt32Property)
  ))
_sym_db.RegisterMessage(UInt32Property)

UInt64Property = _reflection.GeneratedProtocolMessageType('UInt64Property', (_message.Message,), dict(
  DESCRIPTOR = _UINT64PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.UInt64Property)
  ))
_sym_db.RegisterMessage(UInt64Property)

SInt32Property = _reflection.GeneratedProtocolMessageType('SInt32Property', (_message.Message,), dict(
  DESCRIPTOR = _SINT32PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.SInt32Property)
  ))
_sym_db.RegisterMessage(SInt32Property)

SInt64Property = _reflection.GeneratedProtocolMessageType('SInt64Property', (_message.Message,), dict(
  DESCRIPTOR = _SINT64PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.SInt64Property)
  ))
_sym_db.RegisterMessage(SInt64Property)

Fixed32Property = _reflection.GeneratedProtocolMessageType('Fixed32Property', (_message.Message,), dict(
  DESCRIPTOR = _FIXED32PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Fixed32Property)
  ))
_sym_db.RegisterMessage(Fixed32Property)

Fixed64Property = _reflection.GeneratedProtocolMessageType('Fixed64Property', (_message.Message,), dict(
  DESCRIPTOR = _FIXED64PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Fixed64Property)
  ))
_sym_db.RegisterMessage(Fixed64Property)

SFixed32Property = _reflection.GeneratedProtocolMessageType('SFixed32Property', (_message.Message,), dict(
  DESCRIPTOR = _SFIXED32PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.SFixed32Property)
  ))
_sym_db.RegisterMessage(SFixed32Property)

SFixed64Property = _reflection.GeneratedProtocolMessageType('SFixed64Property', (_message.Message,), dict(
  DESCRIPTOR = _SFIXED64PROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.SFixed64Property)
  ))
_sym_db.RegisterMessage(SFixed64Property)

BoolProperty = _reflection.GeneratedProtocolMessageType('BoolProperty', (_message.Message,), dict(
  DESCRIPTOR = _BOOLPROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.BoolProperty)
  ))
_sym_db.RegisterMessage(BoolProperty)

StringProperty = _reflection.GeneratedProtocolMessageType('StringProperty', (_message.Message,), dict(
  DESCRIPTOR = _STRINGPROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.StringProperty)
  ))
_sym_db.RegisterMessage(StringProperty)

StringListProperty = _reflection.GeneratedProtocolMessageType('StringListProperty', (_message.Message,), dict(
  DESCRIPTOR = _STRINGLISTPROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.StringListProperty)
  ))
_sym_db.RegisterMessage(StringListProperty)

BytesProperty = _reflection.GeneratedProtocolMessageType('BytesProperty', (_message.Message,), dict(
  DESCRIPTOR = _BYTESPROPERTY,
  __module__ = 'CallMeMaybe.CommonMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.BytesProperty)
  ))
_sym_db.RegisterMessage(BytesProperty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))
# @@protoc_insertion_point(module_scope)
