# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RPCMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CallMeMaybe import CommonMessages_pb2 as CallMeMaybe_dot_CommonMessages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RPCMessages.proto',
  package='Devialet.CallMeMaybe',
  syntax='proto2',
  serialized_pb=_b('\n\x11RPCMessages.proto\x12\x14\x44\x65vialet.CallMeMaybe\x1a CallMeMaybe/CommonMessages.proto\"b\n\x07Request\x12\x10\n\x08serverId\x18\x01 \x02(\x0c\x12\x11\n\tserviceId\x18\x02 \x02(\x07\x12\x11\n\trequestId\x18\x03 \x02(\x0c\x12\x0c\n\x04type\x18\x04 \x02(\r\x12\x11\n\tsubTypeId\x18\x05 \x02(\r\"\x88\x01\n\x05Reply\x12\x10\n\x08serverId\x18\x01 \x02(\x0c\x12\x11\n\tserviceId\x18\x02 \x02(\x07\x12\x11\n\trequestId\x18\x03 \x02(\x0c\x12\x0c\n\x04type\x18\x04 \x02(\r\x12\x11\n\tsubTypeId\x18\x05 \x02(\r\x12\x11\n\terrorCode\x18\x06 \x02(\x11\x12\x13\n\x0bisMultipart\x18\x07 \x02(\x08\"M\n\x05\x45vent\x12\x10\n\x08serverId\x18\x01 \x02(\x0c\x12\x11\n\tserviceId\x18\x02 \x02(\x07\x12\x0c\n\x04type\x18\x03 \x02(\r\x12\x11\n\tsubTypeId\x18\x04 \x02(\r\"$\n\x11\x43onnectionRequest\x12\x0f\n\x07version\x18\x01 \x02(\r\"#\n\x07Service\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x02(\t\"?\n\x0cServicesList\x12/\n\x08services\x18\x01 \x03(\x0b\x32\x1d.Devialet.CallMeMaybe.Service\"T\n\x0f\x43onnectionReply\x12\x10\n\x08serverId\x18\x01 \x02(\x0c\x12/\n\x08services\x18\x02 \x03(\x0b\x32\x1d.Devialet.CallMeMaybe.Service\"2\n\x10\x43onnectionErrors\"\x1e\n\x04\x43ode\x12\x16\n\x12UnsupportedVersion\x10\x00\x32\x9c\x03\n\nConnection\x12\x62\n\x0eopenConnection\x12\'.Devialet.CallMeMaybe.ConnectionRequest\x1a%.Devialet.CallMeMaybe.ConnectionReply\"\x00\x12\x42\n\x04ping\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12L\n\x0cserviceAdded\x12\x1d.Devialet.CallMeMaybe.Service\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12N\n\x0eserviceRemoved\x12\x1d.Devialet.CallMeMaybe.Service\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12H\n\nserverQuit\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00')
  ,
  dependencies=[CallMeMaybe_dot_CommonMessages__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONNECTIONERRORS_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Devialet.CallMeMaybe.ConnectionErrors.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnsupportedVersion', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=641,
  serialized_end=671,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONERRORS_CODE)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Devialet.CallMeMaybe.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='Devialet.CallMeMaybe.Request.serverId', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceId', full_name='Devialet.CallMeMaybe.Request.serviceId', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='Devialet.CallMeMaybe.Request.requestId', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.CallMeMaybe.Request.type', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subTypeId', full_name='Devialet.CallMeMaybe.Request.subTypeId', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=175,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='Devialet.CallMeMaybe.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='Devialet.CallMeMaybe.Reply.serverId', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceId', full_name='Devialet.CallMeMaybe.Reply.serviceId', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='Devialet.CallMeMaybe.Reply.requestId', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.CallMeMaybe.Reply.type', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subTypeId', full_name='Devialet.CallMeMaybe.Reply.subTypeId', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='Devialet.CallMeMaybe.Reply.errorCode', index=5,
      number=6, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isMultipart', full_name='Devialet.CallMeMaybe.Reply.isMultipart', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=314,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Devialet.CallMeMaybe.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='Devialet.CallMeMaybe.Event.serverId', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceId', full_name='Devialet.CallMeMaybe.Event.serviceId', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.CallMeMaybe.Event.type', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subTypeId', full_name='Devialet.CallMeMaybe.Event.subTypeId', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=393,
)


_CONNECTIONREQUEST = _descriptor.Descriptor(
  name='ConnectionRequest',
  full_name='Devialet.CallMeMaybe.ConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Devialet.CallMeMaybe.ConnectionRequest.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=431,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='Devialet.CallMeMaybe.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Devialet.CallMeMaybe.Service.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Devialet.CallMeMaybe.Service.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=468,
)


_SERVICESLIST = _descriptor.Descriptor(
  name='ServicesList',
  full_name='Devialet.CallMeMaybe.ServicesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='Devialet.CallMeMaybe.ServicesList.services', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=533,
)


_CONNECTIONREPLY = _descriptor.Descriptor(
  name='ConnectionReply',
  full_name='Devialet.CallMeMaybe.ConnectionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverId', full_name='Devialet.CallMeMaybe.ConnectionReply.serverId', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='services', full_name='Devialet.CallMeMaybe.ConnectionReply.services', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=619,
)


_CONNECTIONERRORS = _descriptor.Descriptor(
  name='ConnectionErrors',
  full_name='Devialet.CallMeMaybe.ConnectionErrors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONNECTIONERRORS_CODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=671,
)

_SERVICESLIST.fields_by_name['services'].message_type = _SERVICE
_CONNECTIONREPLY.fields_by_name['services'].message_type = _SERVICE
_CONNECTIONERRORS_CODE.containing_type = _CONNECTIONERRORS
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['ConnectionRequest'] = _CONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['ServicesList'] = _SERVICESLIST
DESCRIPTOR.message_types_by_name['ConnectionReply'] = _CONNECTIONREPLY
DESCRIPTOR.message_types_by_name['ConnectionErrors'] = _CONNECTIONERRORS

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'RPCMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'RPCMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Reply)
  ))
_sym_db.RegisterMessage(Reply)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'RPCMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Event)
  ))
_sym_db.RegisterMessage(Event)

ConnectionRequest = _reflection.GeneratedProtocolMessageType('ConnectionRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONREQUEST,
  __module__ = 'RPCMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.ConnectionRequest)
  ))
_sym_db.RegisterMessage(ConnectionRequest)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), dict(
  DESCRIPTOR = _SERVICE,
  __module__ = 'RPCMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.Service)
  ))
_sym_db.RegisterMessage(Service)

ServicesList = _reflection.GeneratedProtocolMessageType('ServicesList', (_message.Message,), dict(
  DESCRIPTOR = _SERVICESLIST,
  __module__ = 'RPCMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.ServicesList)
  ))
_sym_db.RegisterMessage(ServicesList)

ConnectionReply = _reflection.GeneratedProtocolMessageType('ConnectionReply', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONREPLY,
  __module__ = 'RPCMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.ConnectionReply)
  ))
_sym_db.RegisterMessage(ConnectionReply)

ConnectionErrors = _reflection.GeneratedProtocolMessageType('ConnectionErrors', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONERRORS,
  __module__ = 'RPCMessages_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.CallMeMaybe.ConnectionErrors)
  ))
_sym_db.RegisterMessage(ConnectionErrors)


# @@protoc_insertion_point(module_scope)
