# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpotifyConnect/SpotifyConnect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CallMeMaybe import CommonMessages_pb2 as CallMeMaybe_dot_CommonMessages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SpotifyConnect/SpotifyConnect.proto',
  package='Devialet.SpotifyConnect',
  syntax='proto2',
  serialized_pb=_b('\n#SpotifyConnect/SpotifyConnect.proto\x12\x17\x44\x65vialet.SpotifyConnect\x1a CallMeMaybe/CommonMessages.proto\"i\n\x12ZeroConfApiRequest\x12\x0e\n\x06method\x18\x01 \x02(\r\x12\x0b\n\x03url\x18\x02 \x02(\t\x12\x0c\n\x04\x62ody\x18\x03 \x02(\x0c\"(\n\x06Method\x12\x0b\n\x07Invalid\x10\x00\x12\x07\n\x03Get\x10\x01\x12\x08\n\x04Post\x10\x02\"\xfd\x01\n\x10ZeroConfApiReply\x12\x12\n\nstatusCode\x18\x01 \x02(\r\x12\x11\n\tlastError\x18\x02 \x02(\r\x12\x0c\n\x04\x62ody\x18\x03 \x02(\x0c\"\xb3\x01\n\nStatusCode\x12\x06\n\x02Ok\x10\x00\x12\x07\n\x03\x42\x61\x64\x10\x01\x12\x0b\n\x07Unknown\x10\x02\x12\x12\n\x0eNotImplemented\x10\x03\x12\x0f\n\x0bLoginFailed\x10\x04\x12\x11\n\rMissingAction\x10\x05\x12\x11\n\rInvalidAction\x10\x06\x12\x14\n\x10InvalidArguments\x10\x07\x12\x14\n\x10NoSpotifySession\x10\x08\x12\x10\n\x0cSpotifyError\x10\t2\xce\x05\n\x05\x41gent\x12t\n\x18handleZeroConfApiRequest\x12+.Devialet.SpotifyConnect.ZeroConfApiRequest\x1a).Devialet.SpotifyConnect.ZeroConfApiReply\"\x00\x12R\n\x0csetBouquetId\x12#.Devialet.CallMeMaybe.BytesProperty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x42\n\x04play\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x43\n\x05pause\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x42\n\x04next\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x46\n\x08previous\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12K\n\x06repeat\x12\".Devialet.CallMeMaybe.BoolProperty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12L\n\x07shuffle\x12\".Devialet.CallMeMaybe.BoolProperty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12K\n\x04seek\x12$.Devialet.CallMeMaybe.UInt32Property\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00')
  ,
  dependencies=[CallMeMaybe_dot_CommonMessages__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ZEROCONFAPIREQUEST_METHOD = _descriptor.EnumDescriptor(
  name='Method',
  full_name='Devialet.SpotifyConnect.ZeroConfApiRequest.Method',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Get', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Post', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=163,
  serialized_end=203,
)
_sym_db.RegisterEnumDescriptor(_ZEROCONFAPIREQUEST_METHOD)

_ZEROCONFAPIREPLY_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='Devialet.SpotifyConnect.ZeroConfApiReply.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ok', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Bad', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NotImplemented', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LoginFailed', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MissingAction', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidAction', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidArguments', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NoSpotifySession', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SpotifyError', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=280,
  serialized_end=459,
)
_sym_db.RegisterEnumDescriptor(_ZEROCONFAPIREPLY_STATUSCODE)


_ZEROCONFAPIREQUEST = _descriptor.Descriptor(
  name='ZeroConfApiRequest',
  full_name='Devialet.SpotifyConnect.ZeroConfApiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='Devialet.SpotifyConnect.ZeroConfApiRequest.method', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='Devialet.SpotifyConnect.ZeroConfApiRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='Devialet.SpotifyConnect.ZeroConfApiRequest.body', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ZEROCONFAPIREQUEST_METHOD,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=203,
)


_ZEROCONFAPIREPLY = _descriptor.Descriptor(
  name='ZeroConfApiReply',
  full_name='Devialet.SpotifyConnect.ZeroConfApiReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='Devialet.SpotifyConnect.ZeroConfApiReply.statusCode', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastError', full_name='Devialet.SpotifyConnect.ZeroConfApiReply.lastError', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='Devialet.SpotifyConnect.ZeroConfApiReply.body', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ZEROCONFAPIREPLY_STATUSCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=459,
)

_ZEROCONFAPIREQUEST_METHOD.containing_type = _ZEROCONFAPIREQUEST
_ZEROCONFAPIREPLY_STATUSCODE.containing_type = _ZEROCONFAPIREPLY
DESCRIPTOR.message_types_by_name['ZeroConfApiRequest'] = _ZEROCONFAPIREQUEST
DESCRIPTOR.message_types_by_name['ZeroConfApiReply'] = _ZEROCONFAPIREPLY

ZeroConfApiRequest = _reflection.GeneratedProtocolMessageType('ZeroConfApiRequest', (_message.Message,), dict(
  DESCRIPTOR = _ZEROCONFAPIREQUEST,
  __module__ = 'SpotifyConnect.SpotifyConnect_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SpotifyConnect.ZeroConfApiRequest)
  ))
_sym_db.RegisterMessage(ZeroConfApiRequest)

ZeroConfApiReply = _reflection.GeneratedProtocolMessageType('ZeroConfApiReply', (_message.Message,), dict(
  DESCRIPTOR = _ZEROCONFAPIREPLY,
  __module__ = 'SpotifyConnect.SpotifyConnect_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.SpotifyConnect.ZeroConfApiReply)
  ))
_sym_db.RegisterMessage(ZeroConfApiReply)


# @@protoc_insertion_point(module_scope)
