# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TooManyFlows/History.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CallMeMaybe import CommonMessages_pb2 as CallMeMaybe_dot_CommonMessages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TooManyFlows/History.proto',
  package='Devialet.TooManyFlows',
  syntax='proto2',
  serialized_pb=_b('\n\x1aTooManyFlows/History.proto\x12\x15\x44\x65vialet.TooManyFlows\x1a CallMeMaybe/CommonMessages.proto\"\x15\n\x06UrlMsg\x12\x0b\n\x03url\x18\x01 \x02(\t\"8\n\x07UrlsMsg\x12-\n\x06tracks\x18\x01 \x03(\x0b\x32\x1d.Devialet.TooManyFlows.UrlMsg2\xad\x02\n\x07History\x12\x43\n\x05\x63lear\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x45\n\x07\x63leared\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12I\n\x0btrackPopped\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12K\n\x0btrackPushed\x12\x1d.Devialet.TooManyFlows.UrlMsg\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00')
  ,
  dependencies=[CallMeMaybe_dot_CommonMessages__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_URLMSG = _descriptor.Descriptor(
  name='UrlMsg',
  full_name='Devialet.TooManyFlows.UrlMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='Devialet.TooManyFlows.UrlMsg.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=108,
)


_URLSMSG = _descriptor.Descriptor(
  name='UrlsMsg',
  full_name='Devialet.TooManyFlows.UrlsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='Devialet.TooManyFlows.UrlsMsg.tracks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=166,
)

_URLSMSG.fields_by_name['tracks'].message_type = _URLMSG
DESCRIPTOR.message_types_by_name['UrlMsg'] = _URLMSG
DESCRIPTOR.message_types_by_name['UrlsMsg'] = _URLSMSG

UrlMsg = _reflection.GeneratedProtocolMessageType('UrlMsg', (_message.Message,), dict(
  DESCRIPTOR = _URLMSG,
  __module__ = 'TooManyFlows.History_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.UrlMsg)
  ))
_sym_db.RegisterMessage(UrlMsg)

UrlsMsg = _reflection.GeneratedProtocolMessageType('UrlsMsg', (_message.Message,), dict(
  DESCRIPTOR = _URLSMSG,
  __module__ = 'TooManyFlows.History_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.UrlsMsg)
  ))
_sym_db.RegisterMessage(UrlsMsg)


# @@protoc_insertion_point(module_scope)
