# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TooManyFlows/Configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CallMeMaybe import CommonMessages_pb2 as CallMeMaybe_dot_CommonMessages__pb2
from TooManyFlows import Identifier_pb2 as TooManyFlows_dot_Identifier__pb2
from CallMeMaybe import CallMeMaybe_pb2 as CallMeMaybe_dot_CallMeMaybe__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TooManyFlows/Configuration.proto',
  package='Devialet.TooManyFlows',
  syntax='proto2',
  serialized_pb=_b('\n TooManyFlows/Configuration.proto\x12\x15\x44\x65vialet.TooManyFlows\x1a CallMeMaybe/CommonMessages.proto\x1a\x1dTooManyFlows/Identifier.proto\x1a\x1d\x43\x61llMeMaybe/CallMeMaybe.proto\"z\n\x10\x41\x64\x64RendererQuery\x12/\n\x07groupId\x18\x01 \x02(\x0b\x32\x1e.Devialet.TooManyFlows.GroupId\x12\x35\n\nrendererId\x18\x02 \x02(\x0b\x32!.Devialet.TooManyFlows.RendererId\"b\n\x12\x43onfigurationError\"L\n\x04\x43ode\x12\x16\n\x12LinkRendererFailed\x10\x01\x12\x18\n\x14UnlinkRendererFailed\x10\x02\x12\x12\n\x0e\x42ouquetIsEmpty\x10\x03\x32\xd0\x05\n\rConfiguration\x12K\n\taddPlayer\x12\x1f.Devialet.TooManyFlows.PlayerId\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12U\n\x0b\x61\x64\x64Renderer\x12\'.Devialet.TooManyFlows.AddRendererQuery\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12N\n\x0cremovePlayer\x12\x1f.Devialet.TooManyFlows.PlayerId\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12R\n\x0eremoveRenderer\x12!.Devialet.TooManyFlows.RendererId\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x43\n\x05reset\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12O\n\nautoSwitch\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\".Devialet.CallMeMaybe.BoolProperty\"\x00\x12R\n\rsetAutoSwitch\x12\".Devialet.CallMeMaybe.BoolProperty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x1a\x8c\x01\x92M\x88\x01\n)com.devialet.toomanyflows.configuration-0\x1a-Devialet.TooManyFlows.ConfigurationError.Code\",\n*\n\x1f\x44\x65vialet.TooManyFlows.BouquetId\x12\x07\x62ouquetB\x03\x90\x01\x01')
  ,
  dependencies=[CallMeMaybe_dot_CommonMessages__pb2.DESCRIPTOR,TooManyFlows_dot_Identifier__pb2.DESCRIPTOR,CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONFIGURATIONERROR_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Devialet.TooManyFlows.ConfigurationError.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LinkRendererFailed', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnlinkRendererFailed', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BouquetIsEmpty', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=301,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_CONFIGURATIONERROR_CODE)


_ADDRENDERERQUERY = _descriptor.Descriptor(
  name='AddRendererQuery',
  full_name='Devialet.TooManyFlows.AddRendererQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupId', full_name='Devialet.TooManyFlows.AddRendererQuery.groupId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rendererId', full_name='Devialet.TooManyFlows.AddRendererQuery.rendererId', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=277,
)


_CONFIGURATIONERROR = _descriptor.Descriptor(
  name='ConfigurationError',
  full_name='Devialet.TooManyFlows.ConfigurationError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIGURATIONERROR_CODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=377,
)

_ADDRENDERERQUERY.fields_by_name['groupId'].message_type = TooManyFlows_dot_Identifier__pb2._GROUPID
_ADDRENDERERQUERY.fields_by_name['rendererId'].message_type = TooManyFlows_dot_Identifier__pb2._RENDERERID
_CONFIGURATIONERROR_CODE.containing_type = _CONFIGURATIONERROR
DESCRIPTOR.message_types_by_name['AddRendererQuery'] = _ADDRENDERERQUERY
DESCRIPTOR.message_types_by_name['ConfigurationError'] = _CONFIGURATIONERROR

AddRendererQuery = _reflection.GeneratedProtocolMessageType('AddRendererQuery', (_message.Message,), dict(
  DESCRIPTOR = _ADDRENDERERQUERY,
  __module__ = 'TooManyFlows.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.AddRendererQuery)
  ))
_sym_db.RegisterMessage(AddRendererQuery)

ConfigurationError = _reflection.GeneratedProtocolMessageType('ConfigurationError', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONERROR,
  __module__ = 'TooManyFlows.Configuration_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.ConfigurationError)
  ))
_sym_db.RegisterMessage(ConfigurationError)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_CONFIGURATION = _descriptor.ServiceDescriptor(
  name='Configuration',
  full_name='Devialet.TooManyFlows.Configuration',
  file=DESCRIPTOR,
  index=0,
  options=_descriptor._ParseOptions(descriptor_pb2.ServiceOptions(), _b('\222M\210\001\n)com.devialet.toomanyflows.configuration-0\032-Devialet.TooManyFlows.ConfigurationError.Code\",\n*\n\037Devialet.TooManyFlows.BouquetId\022\007bouquet')),
  serialized_start=380,
  serialized_end=1100,
  methods=[
  _descriptor.MethodDescriptor(
    name='addPlayer',
    full_name='Devialet.TooManyFlows.Configuration.addPlayer',
    index=0,
    containing_service=None,
    input_type=TooManyFlows_dot_Identifier__pb2._PLAYERID,
    output_type=CallMeMaybe_dot_CommonMessages__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addRenderer',
    full_name='Devialet.TooManyFlows.Configuration.addRenderer',
    index=1,
    containing_service=None,
    input_type=_ADDRENDERERQUERY,
    output_type=CallMeMaybe_dot_CommonMessages__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='removePlayer',
    full_name='Devialet.TooManyFlows.Configuration.removePlayer',
    index=2,
    containing_service=None,
    input_type=TooManyFlows_dot_Identifier__pb2._PLAYERID,
    output_type=CallMeMaybe_dot_CommonMessages__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='removeRenderer',
    full_name='Devialet.TooManyFlows.Configuration.removeRenderer',
    index=3,
    containing_service=None,
    input_type=TooManyFlows_dot_Identifier__pb2._RENDERERID,
    output_type=CallMeMaybe_dot_CommonMessages__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reset',
    full_name='Devialet.TooManyFlows.Configuration.reset',
    index=4,
    containing_service=None,
    input_type=CallMeMaybe_dot_CommonMessages__pb2._EMPTY,
    output_type=CallMeMaybe_dot_CommonMessages__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='autoSwitch',
    full_name='Devialet.TooManyFlows.Configuration.autoSwitch',
    index=5,
    containing_service=None,
    input_type=CallMeMaybe_dot_CommonMessages__pb2._EMPTY,
    output_type=CallMeMaybe_dot_CommonMessages__pb2._BOOLPROPERTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setAutoSwitch',
    full_name='Devialet.TooManyFlows.Configuration.setAutoSwitch',
    index=6,
    containing_service=None,
    input_type=CallMeMaybe_dot_CommonMessages__pb2._BOOLPROPERTY,
    output_type=CallMeMaybe_dot_CommonMessages__pb2._EMPTY,
    options=None,
  ),
])

Configuration = service_reflection.GeneratedServiceType('Configuration', (_service.Service,), dict(
  DESCRIPTOR = _CONFIGURATION,
  __module__ = 'TooManyFlows.Configuration_pb2'
  ))

Configuration_Stub = service_reflection.GeneratedServiceStubType('Configuration_Stub', (Configuration,), dict(
  DESCRIPTOR = _CONFIGURATION,
  __module__ = 'TooManyFlows.Configuration_pb2'
  ))


# @@protoc_insertion_point(module_scope)
