# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TooManyFlows/Playback.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CallMeMaybe import CommonMessages_pb2 as CallMeMaybe_dot_CommonMessages__pb2
from CallMeMaybe import CallMeMaybe_pb2 as CallMeMaybe_dot_CallMeMaybe__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TooManyFlows/Playback.proto',
  package='Devialet.TooManyFlows',
  syntax='proto2',
  serialized_pb=_b('\n\x1bTooManyFlows/Playback.proto\x12\x15\x44\x65vialet.TooManyFlows\x1a CallMeMaybe/CommonMessages.proto\x1a\x1d\x43\x61llMeMaybe/CallMeMaybe.proto\"\x19\n\x08IndexMsg\x12\r\n\x05value\x18\x01 \x02(\r\"4\n\x0eProgressionMsg\x12\x10\n\x08position\x18\x01 \x02(\x03\x12\x10\n\x08\x64uration\x18\x02 \x02(\x03\"F\n\x08StateMsg\x12\x0c\n\x04type\x18\x01 \x02(\r\",\n\x04Type\x12\n\n\x06Paused\x10\x01\x12\x0b\n\x07Playing\x10\x02\x12\x0b\n\x07Stopped\x10\x03\"\x19\n\x07SeekMsg\x12\x0e\n\x06offset\x18\x01 \x02(\x03\"}\n\rPlaybackError\"l\n\x04\x43ode\x12\x16\n\x12LinkRendererFailed\x10\x01\x12\x18\n\x14UnlinkRendererFailed\x10\x02\x12\x17\n\x13NoAvailablePlayback\x10\x03\x12\x19\n\x15RequestAlreadyRunning\x10\x04\x32\xa5\x06\n\x08Playback\x12\x44\n\x02\x61t\x12\x1f.Devialet.TooManyFlows.IndexMsg\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x42\n\x04next\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x43\n\x05pause\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x42\n\x04play\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x42\n\x04prev\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x45\n\x04seek\x12\x1e.Devialet.TooManyFlows.SeekMsg\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12\x42\n\x04stop\x12\x1b.Devialet.CallMeMaybe.Empty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x12N\n\x07playUrl\x12$.Devialet.CallMeMaybe.StringProperty\x1a\x1b.Devialet.CallMeMaybe.Empty\"\x00\x1a\xe6\x01\x92M\xe2\x01\n$com.devialet.toomanyflows.playback-0\x1a(Devialet.TooManyFlows.PlaybackError.Code\"\x8f\x01\n)\n!Devialet.CallMeMaybe.BoolProperty\x12\x04loop\n7\n$Devialet.TooManyFlows.ProgressionMsg\x12\x0bprogression\x18\x01(\x00\n)\n\x1e\x44\x65vialet.TooManyFlows.StateMsg\x12\x05state\x18\x01')
  ,
  dependencies=[CallMeMaybe_dot_CommonMessages__pb2.DESCRIPTOR,CallMeMaybe_dot_CallMeMaybe__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STATEMSG_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Devialet.TooManyFlows.StateMsg.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Paused', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Playing', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Stopped', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=226,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_STATEMSG_TYPE)

_PLAYBACKERROR_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Devialet.TooManyFlows.PlaybackError.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LinkRendererFailed', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnlinkRendererFailed', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NoAvailablePlayback', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RequestAlreadyRunning', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=316,
  serialized_end=424,
)
_sym_db.RegisterEnumDescriptor(_PLAYBACKERROR_CODE)


_INDEXMSG = _descriptor.Descriptor(
  name='IndexMsg',
  full_name='Devialet.TooManyFlows.IndexMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Devialet.TooManyFlows.IndexMsg.value', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=144,
)


_PROGRESSIONMSG = _descriptor.Descriptor(
  name='ProgressionMsg',
  full_name='Devialet.TooManyFlows.ProgressionMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='Devialet.TooManyFlows.ProgressionMsg.position', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='Devialet.TooManyFlows.ProgressionMsg.duration', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=198,
)


_STATEMSG = _descriptor.Descriptor(
  name='StateMsg',
  full_name='Devialet.TooManyFlows.StateMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Devialet.TooManyFlows.StateMsg.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATEMSG_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=270,
)


_SEEKMSG = _descriptor.Descriptor(
  name='SeekMsg',
  full_name='Devialet.TooManyFlows.SeekMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='Devialet.TooManyFlows.SeekMsg.offset', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=297,
)


_PLAYBACKERROR = _descriptor.Descriptor(
  name='PlaybackError',
  full_name='Devialet.TooManyFlows.PlaybackError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLAYBACKERROR_CODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=424,
)

_STATEMSG_TYPE.containing_type = _STATEMSG
_PLAYBACKERROR_CODE.containing_type = _PLAYBACKERROR
DESCRIPTOR.message_types_by_name['IndexMsg'] = _INDEXMSG
DESCRIPTOR.message_types_by_name['ProgressionMsg'] = _PROGRESSIONMSG
DESCRIPTOR.message_types_by_name['StateMsg'] = _STATEMSG
DESCRIPTOR.message_types_by_name['SeekMsg'] = _SEEKMSG
DESCRIPTOR.message_types_by_name['PlaybackError'] = _PLAYBACKERROR

IndexMsg = _reflection.GeneratedProtocolMessageType('IndexMsg', (_message.Message,), dict(
  DESCRIPTOR = _INDEXMSG,
  __module__ = 'TooManyFlows.Playback_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.IndexMsg)
  ))
_sym_db.RegisterMessage(IndexMsg)

ProgressionMsg = _reflection.GeneratedProtocolMessageType('ProgressionMsg', (_message.Message,), dict(
  DESCRIPTOR = _PROGRESSIONMSG,
  __module__ = 'TooManyFlows.Playback_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.ProgressionMsg)
  ))
_sym_db.RegisterMessage(ProgressionMsg)

StateMsg = _reflection.GeneratedProtocolMessageType('StateMsg', (_message.Message,), dict(
  DESCRIPTOR = _STATEMSG,
  __module__ = 'TooManyFlows.Playback_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.StateMsg)
  ))
_sym_db.RegisterMessage(StateMsg)

SeekMsg = _reflection.GeneratedProtocolMessageType('SeekMsg', (_message.Message,), dict(
  DESCRIPTOR = _SEEKMSG,
  __module__ = 'TooManyFlows.Playback_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.SeekMsg)
  ))
_sym_db.RegisterMessage(SeekMsg)

PlaybackError = _reflection.GeneratedProtocolMessageType('PlaybackError', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBACKERROR,
  __module__ = 'TooManyFlows.Playback_pb2'
  # @@protoc_insertion_point(class_scope:Devialet.TooManyFlows.PlaybackError)
  ))
_sym_db.RegisterMessage(PlaybackError)


# @@protoc_insertion_point(module_scope)
